export const ActionTypes = {
  REQUEST_GET_PRODUCTS: 'products/REQUEST_GET_PRODUCTS',
  SUCCESS_GET_PRODUCTS: 'products/SUCCESS_GET_PRODUCTS',
  FAILURE_GET_PRODUCTS: 'products/FAILURE_GET_PRODUCTS',
};
